export interface EmployeeI {
    id?:string;
    fullname:string;
    email:string;
    gender:string;
    mobile:string;
    id_depto:string;
    department:string;
    ispermanent:boolean;
    hiredate:Date;
    city:string;
    fotografia:any;
    fileRef?:string;
    userID?:string;
    id_puesto:string;
    puesto:string;
    id_company:string;
    company_name:string;
}
